name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: Dependencies
        run: go get .

      - name: Lipo
        uses: MrOctopus/download-asset-action@1.1
        with:
          repository: konoui/lipo
          asset: lipo_linux_amd64

      - name: Compile
        run: |
          GOARCH=amd64 GOOS=windows go build -ldflags="-s -w" -o updater.exe main.go
          GOARCH=amd64 GOOS=linux go build -ldflags="-s -w" -o updater-linux main.go
          GOARCH=amd64 GOOS=darwin go build -ldflags="-s -w" -o updater-mac-amd main.go
          GOARCH=arm64 GOOS=darwin go build -ldflags="-s -w" -o updater-mac-arm main.go
          mv lipo_linux_amd64 lipo
          chmod +x lipo
          ./lipo -output updater-mac -create updater-mac-arm updater-mac-amd

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          fail_on_unmatched_files: true
          files: |
            updater.exe
            updater-linux
            updater-mac
